import HavanCard from "@/components/HavanCard";
import { havans } from "@/data/havans";
import Seo from "@/components/Seo";
import SeoCta from "@/components/SeoCta";
import WhatsAppIcon from "@/components/icons/WhatsAppIcon";
import { Link } from "react-router-dom";
import { Phone } from "lucide-react";
import { PHONE_TEL_HREF, WHATSAPP_URL } from "@/lib/contact";

const sections = [
  {
    hiTitle: "माँ बगलामुखी का महत्व",
    hi: "माँ बगलामुखी दस महाविद्याओं में अत्यंत पूजनीय देवी हैं और उन्हें स्तंभन शक्ति की अधिष्ठात्री माना जाता है। भक्त जब जीवन में विरोध, झूठे आरोप, भय, मानसिक अशांति, व्यापारिक रुकावट या न्यायालय से जुड़े तनाव का अनुभव करते हैं, तब माँ बगलामुखी की साधना उन्हें धैर्य और आंतरिक बल देती है। नलखेड़ा मंदिर, मध्य प्रदेश में माँ की उपासना का विशेष महत्व माना जाता है, इसलिए यहाँ से जुड़ी बगलामुखी पूजा भक्तों को परंपरा और श्रद्धा से जोड़ती है। यह साधना किसी को हानि पहुँचाने के लिए नहीं, बल्कि अन्यायपूर्ण विरोध को शांत करने, सत्य की रक्षा करने और जीवन को सकारात्मक दिशा देने के लिए की जाती है। बगलामुखी हवन में भक्त अपने नाम, गोत्र और उद्देश्य के साथ संकल्प करता है। उस संकल्प के आधार पर मंत्र जाप, पूजन और आहुति दी जाती है। जब साधक श्रद्धा, नियम और सात्विक भावना से पूजा करवाता है, तब उसके भीतर साहस, स्पष्टता और आत्मविश्वास बढ़ता है। माँ बगलामुखी की कृपा को वाणी, बुद्धि और नकारात्मक प्रभावों पर नियंत्रण की शक्ति के रूप में समझा जाता है। इसलिए यह हवन उन लोगों के लिए महत्वपूर्ण माना जाता है जो भय से निकलकर धर्म, सत्य और स्थिरता के मार्ग पर आगे बढ़ना चाहते हैं।",
    enTitle: "Importance of Maa Baglamukhi",
    en: "Maa Baglamukhi is a deeply revered goddess among the ten Mahavidyas and is known as the presiding power of stambhan, the sacred force of stillness and control. When devotees face opposition, false allegations, fear, mental unrest, business obstacles, or legal stress, the worship of Maa Baglamukhi gives them patience and inner strength. The Nalkheda temple in Madhya Pradesh is considered a significant center of her worship, and Baglamukhi Puja connected with this sacred place links devotees with tradition and faith. This practice is not meant to harm anyone; it is performed to calm unfair opposition, protect truth, and guide life in a positive direction. In Baglamukhi Havan, the devotee makes a sankalp with name, gotra, and purpose. Based on that sankalp, mantra chanting, worship, and sacred offerings are performed. When a devotee takes part with faith, discipline, and pure intention, courage, clarity, and confidence increase within the mind. The grace of Maa Baglamukhi is understood as the power to control harmful speech, disturbed intellect, and negative influences. That is why this havan is considered important for those who want to move beyond fear and walk on the path of dharma, truth, and stability."
  },
  {
    hiTitle: "हवन क्या होता है",
    hi: "हवन एक पवित्र अग्नि अनुष्ठान है जिसमें मंत्र, आहुति, संकल्प और श्रद्धा के माध्यम से देव शक्ति का आवाहन किया जाता है। बगलामुखी हवन में अग्नि को साक्षी मानकर माँ बगलामुखी से रक्षा, विजय, मानसिक शांति और बाधा निवारण की प्रार्थना की जाती है। यह प्रक्रिया केवल सामग्री डालने तक सीमित नहीं होती; इसमें शुद्ध उच्चारण, सही विधि, पवित्र स्थान, योग्य पंडित और भक्त का स्पष्ट उद्देश्य आवश्यक होता है। पहले गणेश पूजन, गुरु वंदना, कलश स्थापना और नवग्रह शांति की जाती है। इसके बाद माँ बगलामुखी का आवाहन कर बीज मंत्रों का जाप किया जाता है। घी, हल्दी, पीली सामग्री, पुष्प, नारियल और विशेष हवन द्रव्य से आहुति दी जाती है। हवन का उद्देश्य जीवन में फैली नकारात्मकता को शांत करना और साधक के संकल्प को दिव्य ऊर्जा से जोड़ना होता है। बगलामुखी हवन विशेष रूप से उन भक्तों के लिए कराया जाता है जिन्हें शत्रु बाधा, कोर्ट केस, व्यापारिक विरोध, तंत्र प्रभाव, नजर दोष या लगातार रुकावटों का सामना करना पड़ रहा हो। यह पूजा व्यक्ति को कर्म, संयम और सकारात्मक सोच की प्रेरणा भी देती है। सही मार्गदर्शन में किया गया हवन भय नहीं बढ़ाता, बल्कि भक्त को विश्वास और संतुलन देता है।",
    enTitle: "What is Havan",
    en: "Havan is a sacred fire ritual in which divine energy is invoked through mantras, offerings, sankalp, and devotion. In Baglamukhi Havan, the sacred fire becomes a witness while the devotee prays to Maa Baglamukhi for protection, victory, mental peace, and removal of obstacles. This process is not limited to placing materials into the fire; it requires pure pronunciation, correct method, a sanctified place, a qualified pandit, and a clear purpose from the devotee. First, Ganesh Puja, Guru Vandana, Kalash Sthapana, and Navgrah Shanti are performed. After this, Maa Baglamukhi is invoked and her beej mantras are chanted. Offerings of ghee, turmeric, yellow materials, flowers, coconut, and special havan ingredients are placed in the fire. The purpose of the havan is to calm negativity in life and connect the devotee’s sankalp with divine energy. Baglamukhi Havan is especially performed for devotees facing enemy problems, court cases, business opposition, tantra-related effects, nazar dosh, or repeated obstacles. This puja also inspires a person toward action, discipline, and positive thinking. A havan performed with proper guidance does not increase fear; it gives the devotee trust and emotional balance."
  },
  {
    hiTitle: "हवन के प्रकार",
    hi: "बगलामुखी साधना में भक्त की परिस्थिति के अनुसार अलग-अलग प्रकार के हवन किए जाते हैं। लाल मिर्च हवन तीव्र नकारात्मक ऊर्जा, तंत्र बाधा, नजर दोष और अचानक बढ़े विरोध की स्थिति में कराया जाता है। इसमें विशेष विधि से लाल मिर्च और अन्य सामग्री की आहुति दी जाती है, इसलिए इसे अनुभवी पंडित के मार्गदर्शन में ही करवाना चाहिए। विजय हवन महत्वपूर्ण कार्यों, प्रतियोगिता, राजनीति, नौकरी, व्यापार और सम्मान से जुड़े संकल्पों के लिए किया जाता है। यह साधक को आत्मबल, धैर्य और सही निर्णय की दिशा में प्रेरित करता है। शत्रु नाश हवन का अर्थ किसी व्यक्ति को नुकसान पहुँचाना नहीं है; इसका उद्देश्य अन्यायपूर्ण विरोध, झूठी बातों, अपमान और भय से रक्षा की प्रार्थना करना है। कोर्ट केस हवन में भक्त न्याय, सत्य और अनुकूल निर्णय के लिए माँ से प्रार्थना करता है। सामान्य बगलामुखी हवन परिवार की शांति, मानसिक स्थिरता, सुरक्षा और आध्यात्मिक शक्ति के लिए भी करवाया जाता है। सही हवन का चयन समस्या की गंभीरता, भक्त के संकल्प, मुहूर्त और पंडित जी के मार्गदर्शन से होता है। इसलिए बिना समझे किसी भी उग्र साधना का चयन नहीं करना चाहिए।",
    enTitle: "Types of Havan",
    en: "Different types of havan are performed in Baglamukhi worship according to the devotee’s situation. Lal Mirch Havan is performed in conditions of intense negative energy, tantra-related disturbance, nazar dosh, and sudden opposition. Red chilies and other special materials are offered through a defined method, so this ritual should be performed only under the guidance of an experienced pandit. Vijay Havan is performed for important work, competition, politics, job, business, and matters connected with respect and recognition. It inspires the devotee toward confidence, patience, and right decisions. Shatru Nash Havan does not mean harming any person; its purpose is to pray for protection from unfair opposition, false statements, humiliation, and fear. In court case havan, the devotee prays to Maa for justice, truth, and a favorable direction. A general Baglamukhi Havan may also be performed for family peace, mental stability, protection, and spiritual strength. The right havan is selected according to the seriousness of the problem, the devotee’s sankalp, muhurat, and the guidance of the pandit. Therefore, no intense spiritual practice should be chosen without proper understanding."
  },
  {
    hiTitle: "हवन के लाभ",
    hi: "बगलामुखी हवन के लाभ भक्त की श्रद्धा, संकल्प, कर्म और परिस्थिति के अनुसार अनुभव किए जाते हैं। भक्त इसे कोर्ट केस में मानसिक धैर्य, सही सलाह और न्यायपूर्ण दिशा के लिए करवाते हैं। जिन लोगों को शत्रु बाधा, झूठे आरोप, सामाजिक अपमान या कार्यस्थल पर विरोध का सामना करना पड़ता है, वे बगलामुखी हवन for enemies के रूप में इस साधना का मार्गदर्शन लेते हैं। व्यापार में रुकावट, पेमेंट अटकना, साझेदारी में तनाव या प्रतिस्पर्धियों के दबाव में भी यह पूजा आत्मबल देती है। परिवार में अशांति, भय, नकारात्मक वातावरण, नजर दोष या बार-बार असफलता की स्थिति में हवन मन को शांत करता है और व्यक्ति को सकारात्मक कर्म की ओर प्रेरित करता है। baglamukhi havan benefits को केवल चमत्कार के रूप में नहीं समझना चाहिए। यह साधना भक्त को संयम, वाणी पर नियंत्रण, सही निर्णय, धैर्य और मानसिक सुरक्षा का अनुभव देती है। हवन के बाद भक्त को सत्य, अनुशासन, सात्विक व्यवहार और सही प्रयास बनाए रखना चाहिए। माँ बगलामुखी की कृपा का अर्थ है भय से मुक्ति, आत्मविश्वास की वृद्धि और धर्मसम्मत विजय की दिशा में आगे बढ़ना।",
    enTitle: "Benefits of Havan",
    en: "The benefits of Baglamukhi Havan are experienced according to the devotee’s faith, sankalp, actions, and circumstances. Devotees perform it for mental patience, proper guidance, and a just direction in court cases. People facing enemy problems, false allegations, social humiliation, or workplace opposition seek guidance for this practice as Baglamukhi Havan for enemies. It also gives inner strength in business obstacles, delayed payments, partnership stress, or pressure from competitors. In situations of family unrest, fear, negative atmosphere, nazar dosh, or repeated failures, the havan calms the mind and inspires the person toward positive action. Baglamukhi Havan benefits should not be understood only as miracles. This practice gives the devotee a sense of discipline, control over speech, right decision-making, patience, and mental protection. After the havan, the devotee should continue truth, discipline, pure conduct, and proper effort. The grace of Maa Baglamukhi means freedom from fear, growth of confidence, and movement toward righteous victory."
  },
  {
    hiTitle: "हवन की विधि",
    hi: "बगलामुखी हवन की विधि संकल्प से आरंभ होती है। भक्त का नाम, गोत्र, स्थान, उद्देश्य और यदि उपलब्ध हो तो जन्म विवरण लेकर पंडित जी संकल्प करते हैं। इसके बाद गणेश पूजन द्वारा विघ्नों की शांति की प्रार्थना की जाती है। गुरु वंदना, कलश स्थापना, मातृका पूजन और नवग्रह शांति के बाद माँ बगलामुखी का आवाहन किया जाता है। पूजन में पीले वस्त्र, हल्दी, पीले पुष्प, चने की दाल, नारियल, दीप, धूप और विशेष हवन सामग्री का प्रयोग होता है। निर्धारित मंत्रों का जाप शुद्ध उच्चारण से किया जाता है। इसके बाद अग्नि में घी और सामग्री की आहुति दी जाती है। लाल मिर्च हवन या शत्रु नाश हवन जैसी विशेष साधनाओं में सामग्री और मंत्र क्रम अलग हो सकता है, इसलिए अनुभवी पंडित का मार्गदर्शन आवश्यक है। अंत में पूर्णाहुति, आरती, क्षमा प्रार्थना और प्रसाद अर्पण होता है। यदि भक्त नलखेड़ा मंदिर नहीं आ सकते, तो फोन या व्हाट्सएप से जानकारी देकर havan booking कर सकते हैं। पूजा के बाद भक्त को अपडेट, प्रसाद या आवश्यक मार्गदर्शन दिया जा सकता है। विधि का मूल आधार शुद्धता, श्रद्धा और स्पष्ट संकल्प है।",
    enTitle: "Havan Vidhi",
    en: "The method of Baglamukhi Havan begins with sankalp. The pandit takes the devotee’s name, gotra, location, purpose, and birth details if available before making the sankalp. After this, Ganesh Puja is performed to pray for the removal of obstacles. Guru Vandana, Kalash Sthapana, Matrika Puja, and Navgrah Shanti are followed by the invocation of Maa Baglamukhi. Yellow cloth, turmeric, yellow flowers, gram lentils, coconut, lamp, incense, and special havan materials are used in the puja. The selected mantras are chanted with pure pronunciation. After that, ghee and sacred materials are offered into the fire. In special practices such as Lal Mirch Havan or Shatru Nash Havan, the material and mantra sequence may be different, so guidance from an experienced pandit is necessary. The ritual ends with purnahuti, aarti, forgiveness prayer, and prasad offering. If devotees cannot visit the Nalkheda temple, they can complete havan booking by sharing details through phone or WhatsApp. After the puja, updates, prasad, or necessary guidance may be provided. The foundation of the method is purity, devotion, and a clear sankalp."
  }
];

const faqs = [
  { hiTitle: "क्या बगलामुखी हवन कोर्ट केस के लिए किया जाता है", hi: "हाँ, भक्त न्याय, धैर्य और सही दिशा की प्रार्थना के लिए कोर्ट केस हवन करवाते हैं।", enTitle: "Is Baglamukhi Havan performed for court cases", en: "Yes, devotees perform court case havan to pray for justice, patience, and the right direction." },
  { hiTitle: "क्या ऑनलाइन हवन बुकिंग हो सकती है", hi: "हाँ, फोन या व्हाट्सएप से जानकारी भेजकर नलखेड़ा, मध्य प्रदेश से जुड़ी पूजा बुक की जा सकती है।", enTitle: "Can havan booking be done online", en: "Yes, puja connected with Nalkheda, Madhya Pradesh can be booked by sharing details through phone or WhatsApp." },
  { hiTitle: "लाल मिर्च हवन कब करवाना चाहिए", hi: "तीव्र नकारात्मकता, तंत्र बाधा, नजर दोष या गंभीर विरोध की स्थिति में पंडित जी से सलाह लेकर इसे करवाया जाता है।", enTitle: "When should Lal Mirch Havan be performed", en: "It is performed after consulting the pandit in cases of intense negativity, tantra disturbance, nazar dosh, or serious opposition." }
];

const HavanTypes = () => (
  <main className="pb-16 bg-background">
    <Seo title="Baglamukhi Havan in Nalkheda | Havan Types & Vidhi" description="Detailed Hindi and English guide for Baglamukhi Havan, Lal Mirch Havan, court case havan, benefits, vidhi and booking in Nalkheda temple." path="/havan" keywords="baglamukhi havan, baglamukhi puja, lal mirch havan, court case havan, nalkheda temple" />
    <section className="py-16 bg-secondary">
      <div className="container mx-auto px-4 text-center">
        <h1 className="text-3xl md:text-4xl font-bold mb-3 text-primary">बगलामुखी हवन के प्रकार और संपूर्ण विवरण</h1>
        <p className="text-foreground/85 max-w-2xl mx-auto">माँ बगलामुखी हवन, लाल मिर्च हवन, विजय हवन, शत्रु नाश हवन और विधि की विस्तृत जानकारी।</p>
        <p className="text-foreground/75 max-w-2xl mx-auto mt-3">Detailed information about Maa Baglamukhi Havan, Lal Mirch Havan, Vijay Havan, Shatru Nash Havan, and the complete method.</p>
        <div className="mt-6 flex flex-col sm:flex-row justify-center gap-3"><Link to="/contact" className="btn-shimmer inline-flex items-center justify-center px-5 py-3 rounded-lg font-bold">Book Now</Link><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 px-5 py-3 rounded-lg font-bold bg-primary/15 text-primary border border-primary/30"><WhatsAppIcon className="h-5 w-5" /> WhatsApp</a><a href={PHONE_TEL_HREF} className="inline-flex items-center justify-center gap-2 px-5 py-3 rounded-lg font-bold bg-primary/15 text-primary border border-primary/30"><Phone className="h-5 w-5" /> Call</a></div>
      </div>
    </section>
    <section className="py-10 bg-background"><div className="container mx-auto px-4 grid md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl">{havans.map((h) => <HavanCard key={h.id} havan={h} />)}</div></section>
    <section className="py-14 bg-secondary"><div className="container mx-auto px-4 max-w-4xl text-foreground/90 leading-relaxed text-sm md:text-base space-y-8">{sections.map((s) => <article key={s.hiTitle} className="space-y-3"><h2 className="text-2xl font-bold text-primary">{s.hiTitle}</h2><p>{s.hi}</p><h2 className="text-2xl font-bold text-primary pt-3">{s.enTitle}</h2><p className="text-foreground/75">{s.en}</p></article>)}<section className="space-y-4"><h2 className="text-2xl font-bold text-primary">अक्सर पूछे जाने वाले प्रश्न</h2><h2 className="text-2xl font-bold text-primary">Frequently Asked Questions</h2>{faqs.map((f) => <div key={f.hiTitle} className="rounded-lg p-4 bg-card/20 border border-primary/25"><h3 className="font-bold mb-1 text-primary">{f.hiTitle}</h3><p className="text-foreground/85 mb-3">{f.hi}</p><h3 className="font-bold mb-1 text-primary">{f.enTitle}</h3><p className="text-foreground/75">{f.en}</p></div>)}</section><p>आगे बढ़ने के लिए <Link to="/anushthan" className="underline text-primary">अनुष्ठान सेवा</Link> पढ़ें और फिर <Link to="/contact" className="underline text-primary">संपर्क पेज</Link> से बुकिंग करें।</p><p className="text-foreground/75">To continue, read the <Link to="/anushthan" className="underline text-primary">Anushthan service</Link> page and then complete booking from the <Link to="/contact" className="underline text-primary">contact page</Link>.</p></div></section>
    <div className="container mx-auto px-4 max-w-3xl"><SeoCta /></div>
  </main>
);

export default HavanTypes;
